name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up GCC
      run: sudo apt-get install -y gcc libsdl2-dev

    - name: Build
      run: make

    - name: Test
      run: ./rotating_cube