jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install SDL2
      run: sudo apt-get install -y libsdl2-dev

    - name: Build the project
      run: gcc rotating_cube.c -o rotating_cube.exe -I"/usr/include/SDL2" -Dmain=SDL_main -lmingw32 -lSDL2main -lSDL2
